// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNDJXnonjMsGGZEaxF_8z50YuJt7edpa0',
    appId: '1:688436199044:web:a841219dd81d8c2ab98cd1',
    messagingSenderId: '688436199044',
    projectId: 'ecom-flutter-78d60',
    authDomain: 'ecom-flutter-78d60.firebaseapp.com',
    storageBucket: 'ecom-flutter-78d60.appspot.com',
    measurementId: 'G-XLV7D7N4YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7t4rbdvIxIlkO_-RhDSXNVFiIKikdySc',
    appId: '1:688436199044:android:f4a45aaa395f5af0b98cd1',
    messagingSenderId: '688436199044',
    projectId: 'ecom-flutter-78d60',
    storageBucket: 'ecom-flutter-78d60.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNDJXnonjMsGGZEaxF_8z50YuJt7edpa0',
    appId: '1:688436199044:web:9ed5293aae9044b3b98cd1',
    messagingSenderId: '688436199044',
    projectId: 'ecom-flutter-78d60',
    authDomain: 'ecom-flutter-78d60.firebaseapp.com',
    storageBucket: 'ecom-flutter-78d60.appspot.com',
    measurementId: 'G-1MZ9YCZZJ2',
  );
}
